### ISSUE TITLE
Cannot find module 'jest-cli/build/SearchSource'

### ISSUE THREAD

**Issue by DamienCassou** [mzgoddard/jest-webpack#21]
I have a very simple project that I just started. After launching jest-webpack, I get:

```
/home/cassou/Documents/projects/ftgp/seamus2/node_modules/jest-webpack/src/try-require.js:9
  throw err;
  ^

Error: Cannot find module 'jest-cli/build/SearchSource'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at tryRequire (/home/cassou/Documents/projects/ftgp/seamus2/node_modules/jest-webpack/src/test-entries-plugin.js:15:9)
    at module.exports._ (/home/cassou/Documents/projects/ftgp/seamus2/node_modules/jest-webpack/src/try-require.js:5:14)
    at Object.<anonymous> (/home/cassou/Documents/projects/ftgp/seamus2/node_modules/jest-webpack/src/test-entries-plugin.js:13:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by mzgoddard** [comment]
Bumped into this myself. You can use an older jest like jest@20 in the
meantime.

**Comment by MFQ** [comment]
I am also getting same error any solution yet?

**Comment by AlexanderTserkovniy** [comment]
Same here, @mzgoddard what the solution?

**Comment by mzgoddard** [comment]
Fix is up in v0.3.1. `SearchSource` was easy to fix. It had moved to `search_source`. After that though were a number of other small and tricky issues.

**Comment by jakubpeksa** [comment]
not working in 0.5.1 version

**Comment by agnathan** [comment]
It is also not working in 0.5.1 for me.
